### ISSUE TITLE
possible crashing

### ISSUE THREAD

**Issue by TeameurekaRobotics** [narlyx/TweetyBird#1]
could this be a culprit somehow that is not allowing full lines of opMode to run?

https://github.com/narlyx/TweetyBird/blob/a9cd3d814d25ee1fc06b16525ba66eb5489d837e/src/main/java/dev/narlyx/tweetybird/TweetyBird.java#L71

**Comment by narlyx** [comment]
So, it seems to be bypassing the wait, however, TweetyBird will wipe the entire queue when it is done moving and I think that is what is causing some commands to be dropped. I added a check to query the queue to make sure that there are no new items since it was last checked and that seems to not be enough.

I made a quick tacky fix last night and it greatly improved the performance and reduced the possibility of the bug occurring, but we still encountered it a few times after the fix.
https://github.com/narlyx/TweetyBird/commit/a9cd3d814d25ee1fc06b16525ba66eb5489d837e

**Comment by narlyx** [comment]
Another thought is that maybe some positional values unpredictably changed, and might have slipped past some of the basic error checking that is implemented. Most of the time when the FTC SDK silently crashes it is likely due to an error occurring in a thread that is not managed by the FTC SDK. I will be implementing a new feature to print all log/debug messages to a file to try and get around the fact that the driver station will wipe all telemetry the second the robot crashes.

**Comment by TeameurekaRobotics** [comment]
Do you know if other teams using TB are experiencing similar issues?

**Comment by narlyx** [comment]
No, not at the moment.

**Comment by narlyx** [comment]
A new commit has been pushed which should resolve this issue: https://github.com/narlyx/TweetyBird/commit/4148f01797a36dacbfa8a4c0821cab7e6178b3c2
